name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *"  # Executa automaticamente a cada 24 horas
  workflow_dispatch:  # Permite execução manual
  push:
    branches:
      - master  # Executa a cada push na branch principal

jobs:
  generate:
    permissions:
      contents: write  # Permite escrever no repositório
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Gerar animação SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MatheusSMariano
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Enviar animação para a branch 'output'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
